config/routes.rb
Rails.application.routes.draw do

  root to: 'grants#home'

  get  'login',  to: 'sessions#new'
  post 'login',  to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'

  resources :grants, except: [:show, :destroy]

  resources :agencies, except: [:show, :destroy]

  resources :applicant_types, except: [:show, :destroy]

  resources :reviews, only: [:index, :show, :create]
  patch 'reviews/:id/approve', to: 'reviews#approve', as: 'review_approve'
  patch 'reviews/:id/reject',  to: 'reviews#reject',  as: 'review_reject'

  get 'sync/grant/:id', to: 'sync#grant', as: 'sync_grant'

  post 'api/import', to: 'api#import'

  post 'grants/validate', to: 'api#validate'

end

app/models/agency.rb
# == Schema Information
#
# Table name: agencies
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  shortname  :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Agency < ApplicationRecord

  has_many :grants

  validates :name, presence: true

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController

  before_action :authorize_admin

  def index
    @agencies = Agency.order(name: :asc)
  end

  def new
    @agency = Agency.new
  end

  def create
    @agency = Agency.new(admin_agency_params)
    if @agency.save
      flash[:success] = 'Agency created successfully'
      redirect_to agencies_path
    else
      flash.now[:error] = @agency.errors.full_messages.first
      render :new
    end
  end

  def edit
    @agency = Agency.find(params[:id])
  end

  def update
    @agency = Agency.find(params[:id])
    if @agency.update_attributes(admin_agency_params)
      flash.now[:success] = 'Agency updated successfully'
    else
      flash.now[:error] = @agency.errors.full_messages.first
    end
    render :edit
  end

  private

  def admin_agency_params
    params.require(:agency).permit(:name, :shortname)
  end

end

app/views/agencies/_form.html.erb
<%= render 'shared/flash' %>

<div class="input-group">
  <%= f.text_field :name, placeholder: 'Name', class: 'text', required: true %>
</div>

<div class="input-group">
  <%= f.text_field :shortname, placeholder: 'Shortname (abbreviation)', class: 'text', required: true %>
</div>

<div class="input-group">
  <button class="button"><%= button_text %></button>
</div>

app/views/agencies/edit.html.erb
<%= form_with model: @agency, url: agency_path(@agency), method: :patch, local: true, class: 'slim' do |f| %>
  <%= render 'form', f: f, button_text: 'Update Agency' %>
<% end %>

app/views/agencies/index.html.erb
<div class="button-row">
  <%= link_to 'New Agency', new_agency_path, class: 'button' %>
</div>

<%= render 'shared/flash' %>

<table class="data">
  <thead>
    <tr>
      <th>ID</th>
      <th>Shortname</th>
      <th>Name</th>
      <th class="center">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @agencies.each do |agency| %>
      <tr>
        <td><%= agency.id %></td>
        <td><%= link_to agency.shortname, edit_agency_path(agency) %></td>
        <td><%= link_to agency.name, edit_agency_path(agency) %></td>
        <td class="center"><%= link_to('edit', edit_agency_path(agency)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/agencies/new.html.erb
<%= form_with model: @agency, url: agencies_path, method: :post, local: true, class: 'slim' do |f| %>
  <%= render 'form', f: f, button_text: 'Create Agency' %>
<% end %>