config/routes.rb
Rails.application.routes.draw do

  root to: 'grants#home'

  get  'login',  to: 'sessions#new'
  post 'login',  to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'

  resources :grants, except: [:show, :destroy]

  resources :agencies, except: [:show, :destroy]

  resources :applicant_types, except: [:show, :destroy]

  resources :reviews, only: [:index, :show, :create]
  patch 'reviews/:id/approve', to: 'reviews#approve', as: 'review_approve'
  patch 'reviews/:id/reject',  to: 'reviews#reject',  as: 'review_reject'

  get 'sync/grant/:id', to: 'sync#grant', as: 'sync_grant'

  post 'api/import', to: 'api#import'

  post 'grants/validate', to: 'api#validate'

end

app/controllers/applicant_types_controller.rb
class ApplicantTypesController < ApplicationController

  before_action :authorize_admin

  def index
    @applicant_types = ApplicantType.all
  end

  def new
    @applicant_type = ApplicantType.new
  end

  def create
    @applicant_type = ApplicantType.new(applicant_type_params)
    if @applicant_type.save
      flash[:success] = 'Applicant type created successfully'
      redirect_to applicant_types_path
    else
      flash.now[:error] = @applicant_type.errors.full_messages.first
      render :new
    end
  end

  def edit
    @applicant_type = ApplicantType.find(params[:id])
  end

  def update
    @applicant_type = ApplicantType.find(params[:id])
    if @applicant_type.update_attributes(applicant_type_params)
      flash.now[:success] = 'Applicant type updated successfully'
    else
      flash.now[:error] = @applicant_type.errors.full_messages.first
    end
    render :edit
  end

  private

  def applicant_type_params
    params.require(:applicant_type).permit(:name)
  end

end

app/views/applicant_types/_form.html.erb
<%= render 'shared/flash' %>

<div class="input-group">
  <%= f.text_field :name, placeholder: 'Type', class: 'text', required: true %>
</div>

<div class="input-group">
  <button class="button"><%= button_text %></button>
</div>

app/views/applicant_types/edit.html.erb
<%= form_with model: @applicant_type, url: applicant_type_path(@applicant_type), method: :patch, local: true, class: 'slim' do |f| %>
  <%= render 'form', f: f, button_text: 'Update Applicant Type' %>
<% end %>

app/views/applicant_types/index.html.erb
<div class="button-row">
  <%= link_to 'New Applicant Type', new_applicant_type_path, class: 'button' %>
</div>

<%= render 'shared/flash' %>

<table class="data">
  <thead>
    <tr>
      <th>ID</th>
      <th>Type</th>
      <th class="center">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @applicant_types.each do |applicant_type| %>
      <tr>
        <td><%= applicant_type.id %></td>
        <td><%= link_to applicant_type.name, edit_applicant_type_path(applicant_type) %></td>
        <td class="center"><%= link_to('edit', edit_applicant_type_path(applicant_type)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/applicant_types/new.html.erb
<%= form_with model: @applicant_type, url: applicant_types_path, method: :post, local: true, class: 'slim' do |f| %>
  <%= render 'form', f: f, button_text: 'Create Applicant Type' %>
<% end %>