config/routes.rb
Rails.application.routes.draw do

  root to: 'grants#home'

  get  'login',  to: 'sessions#new'
  post 'login',  to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'

  resources :grants, except: [:show, :destroy]

  resources :agencies, except: [:show, :destroy]

  resources :applicant_types, except: [:show, :destroy]

  resources :reviews, only: [:index, :show, :create]
  patch 'reviews/:id/approve', to: 'reviews#approve', as: 'review_approve'
  patch 'reviews/:id/reject',  to: 'reviews#reject',  as: 'review_reject'

  get 'sync/grant/:id', to: 'sync#grant', as: 'sync_grant'

  post 'api/import', to: 'api#import'

  post 'grants/validate', to: 'api#validate'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all.includes(:grant).order(created_at: :desc)
  end

  def show
    @review = Review.find(params[:id])
    @preview = CustomMarkdown.new.render(@review.grant.body)
  end

  def create
    # Handles both submissions and resubmissions via first_or_initialize
    grant = current_user.grants.find(params[:grant_id])
    review = current_user.reviews.where(grant: grant).first_or_initialize
    return unprocessable unless current_user.can_submit_review?(review)
    review.status = 'pending'
    review.save
    flash[:success] = 'Successfully submitted for review'
    redirect_to grants_path
  end

  def approve
    review = Review.find(params[:id])
    return unprocessable unless current_user.can_approve_review?(review)
    review.update_attributes!(status: 'approved')
    SyncGrantJob.enqueue(review.grant.id)
    flash[:success] = 'Review has been approved'
    redirect_to reviews_path
  end

  def reject
    review = Review.find(params[:id])
    return unprocessable unless current_user.can_approve_review?(review)
    review.update_attributes!(
      status: 'rejected',
      reviewer_notes: params[:reviewer_notes]
    )
    flash[:success] = 'Review has been rejected'
    redirect_to reviews_path
  end

end

app/views/reviews/index.html.erb
<%= render 'shared/flash' %>

<table class="data">
  <thead>
    <tr>
      <th>ID</th>
      <th>Grant Name</th>
      <th>Status</th>
      <th>Submitted</th>
      <th class="center">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.id %></td>
        <td><%= link_to review.grant.title, review_path(review) %></td>
        <td><%= review.status %></td>
        <td><%= time_ago_in_words(review.created_at) %> ago</td>
        <td class="center"><%= link_to 'audit', review_path(review) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/show.html.erb
<div class="grant-review">
  <h2><%= @review.grant.title %></h2><br>
  <div class="">
    <table class="data">
      <tr>
        <td><strong>Agency</strong></td>
        <td><%= @review.grant.agency.shortname %></td>
      </tr>
      <tr>
        <td><strong>Time Zone</strong></td>
        <td><%= @review.grant.time_zone %></td>
      </tr>
      <tr>
        <td><strong>Sponsor(s)</strong></td>
        <td><%= @review.grant.sponsor %></td>
      </tr>
      <tr>
        <td><strong>Amount</strong></td>
        <td><%= @review.grant.amount %></td>
      </tr>
      <tr>
        <td><strong>Applicant Type</strong></td>
        <td>
          <% @review.grant.applicant_types.each do |type| %>
            <%= type.name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td><strong>Residency</strong></td>
        <td><%= @review.grant.residency %></td>
      </tr>
      <tr>
        <td><strong>Activity Location</strong></td>
        <td><%= @review.grant.activity_location %></td>
      </tr>
    </table><br>

    <span><strong>Deadline(s)</strong></span>
    <table class="data">
      <thead>
        <th>Date</th>
        <th>Item Due</th>
        <th>Notes</th>
      </thead>
      <tbody>
        <% @review.grant.deadlines.each do |deadline| %>
          <tr>
            <td><%= deadline.date %></td>
            <td><%= deadline.item_due %></td>
            <td><%= deadline.notes %></td>
          </tr>
        <% end %>
      </tbody>
    </table><br>
  </div>
  <h4><%= link_to @review.grant.url, @review.grant.url, target: '_blank' %></h4>
</div>

<div class="markdown-preview">
  <h3 class="grant-preview">Live Preview</h3>
  <div class="submit-review">
    <% if @review.pending? %>
      <%= button_to 'Approve and Sync', review_approve_path, method: :patch, class: 'button button-green' %>
      <%= button_to 'Reject with Notes', review_reject_path, method: :patch, class: 'button button-red button-reject' %>
    <% elsif @review.rejected? %>
      <%= button_to 'Pending rewrite', '#', disabled: true, class: 'button button-green' %>
    <% elsif @review.approved? %>
      <%= button_to 'Approved', '#', disabled: true, class: 'button button-green' %>
    <% end %>
  </div>
  <div class="html">
    <% if @preview.present? %>
      <%= @preview.html_safe %>
    <% else %>
      <p>This description has no content...</p>
    <% end %>
  </div>
</div>